# This configuration has been generated by the Azure deployments handler which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

provider "azurerm" {
  features {}
}

resource "azurerm_kubernetes_cluster" "az_kc" {
  name                = var.az_kc_name
  location            = azurerm_resource_group.az_rg.location
  resource_group_name = azurerm_resource_group.az_rg.name
  dns_prefix          = "ec-kube1"

  default_node_pool {
    name       = var.az_kc_default_node_pool_name
    node_count = 3
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = var.az_kc_identity_type
  }

  tags = {
    Environment = "Production"
  }
}