name: Main Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Build
      run: mvn package

    - name: Build & Tag Docker Image
      run: docker build -t {docker-repo} .

    - name: Docker Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '{docker-repo}'
        format: 'table'
        output: 'trivy-image-report.txt'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push {docker-repo}

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment-service.yml
        images: |
          {docker-repo}
        imagepullsecrets: |
          docker-auth
        namespace: webapps

    - name: Verify Deployment
      run: |
        kubectl get pods -n webapps
        kubectl get svc -n webapps

    - name: Send email
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: Deployment of ${{ github.repository }} has ${{ job.status }}
        body: |
          Deployment in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}.
          
          Check the workflow run for more details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: tnt85091023@gmail.com
        from: GitHub Actions
        attachments: trivy-image-report.txt