name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        output: 'fs-report.txt'

    - name: Upload Trivy FS scan results
      uses: actions/upload-artifact@v2
      with:
        name: trivy-fs-results
        path: fs-report.txt